### ISSUE TITLE
env: UAT, failed times: 39, meta server address: http://192.168.0.106:8082

### ISSUE THREAD

**Issue by FriezaKing** [apolloconfig/apollo#3976]
在虚拟机 (centos8.3) 使用docker 分布式部署 apollo

虚拟机使用桥接的方式，虚拟机 ip 地址是 192.168.0.106

安装了 4 个环境 dev fat uat pro

所以我启动了 4 个 apollo-adminservice ， 4 个 pollo-configservice ，和 1 个 apollo-portal ， 还有 4 个 mysql 容器

容器运行情况如下

[root@192 ~]# docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS         PORTS                                                    NAMES
9ea68be7bdb4   apolloconfig/apollo-portal:latest          "/apollo-portal/scri…"   9 minutes ago   Up 9 minutes   0.0.0.0:8070->8070/tcp, :::8070->8070/tcp                apollo-portal
cb6d8f07ee2e   apolloconfig/apollo-adminservice:latest    "/apollo-adminservic…"   2 hours ago     Up 2 hours     0.0.0.0:8090->8090/tcp, :::8090->8090/tcp                apollo-admin-dev
7d677701f531   apolloconfig/apollo-configservice:latest   "/apollo-configservi…"   2 hours ago     Up 2 hours     0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                apollo-config-dev
f9c3e03bb3fb   mysql:latest                               "docker-entrypoint.s…"   2 hours ago     Up 2 hours     33060/tcp, 0.0.0.0:33060->3306/tcp, :::33060->3306/tcp   mysql-apollo-config-dev
637775d532dd   apolloconfig/apollo-adminservice:latest    "/apollo-adminservic…"   2 hours ago     Up 2 hours     0.0.0.0:8093->8090/tcp, :::8093->8090/tcp                apollo-admin-pro
7d82ddc7b55b   apolloconfig/apollo-adminservice:latest    "/apollo-adminservic…"   2 hours ago     Up 2 hours     0.0.0.0:8092->8090/tcp, :::8092->8090/tcp                apollo-admin-uat
8267ed26d347   apolloconfig/apollo-adminservice:latest    "/apollo-adminservic…"   2 hours ago     Up 2 hours     0.0.0.0:8091->8090/tcp, :::8091->8090/tcp                apollo-admin-fat
f7fb2a458b11   apolloconfig/apollo-configservice:latest   "/apollo-configservi…"   2 hours ago     Up 2 hours     0.0.0.0:8083->8080/tcp, :::8083->8080/tcp                apollo-config-pro
728f938da614   apolloconfig/apollo-configservice:latest   "/apollo-configservi…"   2 hours ago     Up 2 hours     0.0.0.0:8082->8080/tcp, :::8082->8080/tcp                apollo-config-uat
c56350438109   apolloconfig/apollo-configservice:latest   "/apollo-configservi…"   2 hours ago     Up 2 hours     0.0.0.0:8081->8080/tcp, :::8081->8080/tcp                apollo-config-fat
d537ea4d0999   mysql:latest                               "docker-entrypoint.s…"   4 hours ago     Up 3 hours     33060/tcp, 0.0.0.0:33064->3306/tcp, :::33064->3306/tcp   mysql-apollo-portal
1029cae2ed36   mysql:latest                               "docker-entrypoint.s…"   4 hours ago     Up 3 hours     33060/tcp, 0.0.0.0:33063->3306/tcp, :::33063->3306/tcp   mysql-apollo-config-pro
dfa7e72c5f4a   mysql:latest                               "docker-entrypoint.s…"   4 hours ago     Up 3 hours     33060/tcp, 0.0.0.0:33062->3306/tcp, :::33062->3306/tcp   mysql-apollo-config-uat
fe2b250c7edf   mysql:latest                               "docker-entrypoint.s…"   4 hours ago     Up 3 hours     33060/tcp, 0.0.0.0:33061->3306/tcp, :::33061->3306/tcp   mysql-apollo-config-fat

然后在本机  http://192.168.0.106:8070/ 登录 Apollo 界面 ，新建一个 应用后进入提示错误

![X9C1CL$QL487HA@9UKL5ZCQ](https://user-images.githubusercontent.com/82102012/132940329-2275a6e8-15d6-471b-8c3b-5f1aefa7020b.png)

管理员工具 系统信息 显示

![%OO)7K$2B @_YNAH3_MFKHD](https://user-images.githubusercontent.com/82102012/132940366-ece98009-fc8e-45d4-aa9f-61798590ef5c.png)

portal 日志:

2021-09-11 15:25:35.563 ERROR 1 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: UAT, failed times: 39, meta server address: http://192.168.0.106:8082
2021-09-11 15:25:35.563 ERROR 1 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: PRO, meta server address: http://192.168.0.106:8083

com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://192.168.0.106:8083
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:228)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:132)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:98)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:43)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:148)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2021-09-11 15:25:35.563 ERROR 1 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: PRO, failed times: 39, meta server address: http://192.168.0.106:8083

**Comment by FriezaKing** [comment]
portal 启动命令

docker run -p 8070:8070 \
    -e SPRING_DATASOURCE_URL="jdbc:mysql://192.168.0.106:33064/ApolloPortalDB?characterEncoding=utf8" \
    -e SPRING_DATASOURCE_USERNAME=apollo \
    -e SPRING_DATASOURCE_PASSWORD=pwd123 \
    -e APOLLO_PORTAL_ENVS=dev,fat,uat,pro \
    -e DEV_META=http://192.168.0.106:8080 \
    -e FAT_META=http://192.168.0.106:8081 \
    -e UAT_META=http://192.168.0.106:8082 \
    -e PRO_META=http://192.168.0.106:8083 \
    -d -v /tmp/logs-portal:/opt/logs \
    --name apollo-portal apolloconfig/apollo-portal:latest

**Comment by nobodyiam** [comment]
看现象是 admin service 没有注册到对应环境的 eureka 上，应该是 apolloconfigdb.serverconfig 中的 eureka.service.url 没有更新为对应环境的 config service ip
