### ISSUE TITLE
开放平台管理后，使用apollo管理界面修改配置失败

### ISSUE THREAD

**Issue by veteran2018** [apolloconfig/apollo#4139]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**问题描述**
使用超级管理员，启用了开放平台授权管理，对指定app的namespace创建了三方管理的token后，在apollo的portal界面，修改配置等编辑权限，执行失败

**apollo服务端日志异常截图**

![image](https://user-images.githubusercontent.com/58755705/145143399-b7851e20-df1a-4d4e-bc7a-4674fdb5f8f1.png)

### 额外的细节和日志

- 版本：apollo版本：1.6.2
- 堆栈信息：Wed Dec 08 10:16:28 CST 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2021-12-08 10:16:36.781  INFO 25942 --- [nio-8090-exec-4] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:428)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:684)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

- 操作系统：CentOS 7.5

**Comment by nobodyiam** [comment]
Would you please provide detailed steps to duplicate this issue? It would be best to duplicate it in the [demo site](http://106.54.227.205/).
