### ISSUE TITLE
NPE occurred when using EnableApolloConfig with Spring 3.1.1

### ISSUE THREAD

**Issue by nobodyiam** [apolloconfig/apollo#4178]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**
When using `@EnableApolloConfig` with Spring 3.1.1, NullPointerException will occur.

**To Reproduce**
1. Mark a configuration class with `@EnableApolloConfig`
```java
@Configuration
@EnableApolloConfig(value = "application", order = 10)
public class AppConfig {
  @Bean
  public NormalBean normalBean(@Value("${batch:100}") int batch) {
    NormalBean bean = new NormalBean();
    bean.setBatch(batch);
    return bean;
  }
}
```

2. Run the application with Spring version 3.1.1
3. NullPointerException will occur
```
Exception in thread "main" java.lang.NullPointerException
	at com.ctrip.framework.apollo.spring.spi.DefaultApolloConfigRegistrarHelper.resolveNamespaces(DefaultApolloConfigRegistrarHelper.java:52)
	at com.ctrip.framework.apollo.spring.spi.DefaultApolloConfigRegistrarHelper.registerBeanDefinitions(DefaultApolloConfigRegistrarHelper.java:29)
	at com.ctrip.framework.apollo.spring.annotation.ApolloConfigRegistrar.registerBeanDefinitions(ApolloConfigRegistrar.java:20)
	at org.springframework.context.annotation.ConfigurationClassParser.processImport(ConfigurationClassParser.java:331)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:228)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:149)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:126)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:263)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:203)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:617)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:446)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at com.ctrip.framework.apollo.demo.spring.AnnotationApplication.main(AnnotationApplication.java:12)
```
4. 

**Expected behavior**
The application should work well

**Screenshots**

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by nobodyiam** [comment]
After some investigation, here is what I found now.

1. The `ApolloConfigRegistrar` and `DefaultApolloConfigRegistrarHelper` are marked `EnvironmentAware ` in #3349
see https://github.com/apolloconfig/apollo/commit/6ce0932082f89fa94637917f147682254b32db82#diff-99cf529f565d3db2b0cb6d6c6a6ccdc92d0404cbb897cb61dcee90636bb12db1R24

2. We use the `Environment` to resolve the namespace placeholders
see https://github.com/apolloconfig/apollo/commit/6ce0932082f89fa94637917f147682254b32db82#diff-0bd5d05308645d08b006bdca711e6954b0305d1315e8b0d4625f2b68337261dbR52

3. However, `ApolloConfigRegistrar` and `DefaultApolloConfigRegistrarHelper` are both of type `ImportBeanDefinitionRegistrar`, which doesn't support `EnvironmentAware` until Spring 3.2.x
see https://github.com/spring-projects/spring-framework/commit/146a66fe0b7a0bb25b67ce5e2d1ca8a33039ec59

4. So the `environment` variable will always be null if running with Spring versions prior to 3.2.x, which explains why npe occurred.
