### ISSUE TITLE
portal 日志打印The valid characters are defined in RFC 7230 and RFC 3986

### ISSUE THREAD

**Issue by hanwlgithub** [apolloconfig/apollo#4233]
- [ ] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

**To Reproduce**
1. 下载  1.9.2 版本portal 在linux系统启动，登录操作页面
2.  日志显示 java.lang.IllegalArgumentException: Invalid character found in the request target [/%7B%7B%20'/img/github.png'%20|%20prefixPath%20%7D%7D]. The valid characters are defined in RFC 7230 and RFC 3986
3. 经查询是tomcat7.0.73 以后版本都会出现，是RFC 3986规范的原因；
4. 

### Additional Details & Logs

- version: 1.9.2
- log: 2022-02-17 17:37:08.181  INFO 22933 --- [http-nio-8070-exec-3] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in the request target [/%7B%7B%20'/img/github.png'%20|%20prefixPath%20%7D%7D]. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:498)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

- Linux version 3.10.0-693.el7.x86_64

**Comment by nobodyiam** [comment]
The server log seems ok to reject this request but it looks like the javascript issue that sends the wrong request. Would you please clear the browser cache and try again? If you are using chrome, you may take a look at the network tab.
