### ISSUE TITLE
使用 OpenApi + LDAP , 人员离职后系统出错了

### ISSUE THREAD

**Issue by klboke** [apolloconfig/apollo#4240]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

用 LDAP + OpenApi 时遇到一个问题，OpenApi 设置的 DataChangeLastModifiedBy 人员离职后，用户信息从 LDAP 删除了，导致用户查询不到校验报错

**期望**

OpenApi 是不是可以不校验 userid 的真实性？我看其他UI查询的时候也没有强制要求 userid 一定会查询到用户。另 OpenApi 也不适合用个人的 userid 设置，比较理想的是可以设置成OpenAPI 所在系统的名称

**异常日志**
人员离职导致的线上环境非预期的异常
```java
com.ctrip.framework.apollo.common.exception.BadRequestException: user(dataChangeLastModifiedBy) not exists
--
Wed, Feb 23 2022 11:18:15 pm | at com.ctrip.framework.apollo.openapi.v1.controller.ItemController.updateItem(ItemController.java:113)
Wed, Feb 23 2022 11:18:15 pm | at com.ctrip.framework.apollo.openapi.v1.controller.ItemController$FastClassBySpringCGLIB$e8be1028.invoke(<generated>)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
Wed, Feb 23 2022 11:18:15 pm | at com.ctrip.framework.apollo.openapi.v1.controller.ItemController$EnhancerBySpringCGLIB$e916f09a.updateItem(<generated>)
Wed, Feb 23 2022 11:18:15 pm | at sun.reflect.GeneratedMethodAccessor298.invoke(Unknown Source)
Wed, Feb 23 2022 11:18:15 pm | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Wed, Feb 23 2022 11:18:15 pm | at java.lang.reflect.Method.invoke(Method.java:498)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
Wed, Feb 23 2022 11:18:15 pm | at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
Wed, Feb 23 2022 11:18:15 pm | at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at com.ctrip.framework.apollo.openapi.filter.ConsumerAuthenticationFilter.doFilter(ConsumerAuthenticationFilter.java:69)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:149)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:141)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
Wed, Feb 23 2022 11:18:15 pm | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
Wed, Feb 23 2022 11:18:15 pm | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Wed, Feb 23 2022 11:18:15 pm | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Wed, Feb 23 2022 11:18:15 pm | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Wed, Feb 23 2022 11:18:15 pm | at java.lang.Thread.run(Thread.java:748)

```

**Comment by nobodyiam** [comment]
UserId is used in many places as a key entity, e.g. display in the change history, release history, etc.
To make the system data clean, I think it's reasonable to check the validity of DataChangeLastModifiedBy.
![image](https://user-images.githubusercontent.com/837658/156084726-b28e8419-8095-4f7e-b6fa-1b24fd0b0a9f.png)

For OpenApi scenarios, though the invoker is a third-party system, I think it should behave on behalf of some actual user and we also need that user information for audit purposes.

BTW, I'm curious about your scenario. What's the actual use case and who initiated the item update?

**Comment by klboke** [comment]
The problem we encountered is like this.
Apollo Server has granted OpenApi-related privileges to app-b, and app-b has configured developer-a's userid as a fixed apollo-user when calling the OpenApi-related interface, but recently developer-a has left the system and the LDAP user has been deleted, resulting in OpenApi verifies the user with an error, and the system cannot run

This scenario has the following problems.

1.  OpenApi is not user-authorized, and OpenApi can set any userid, even if the userid does not have the privilege of the project at all. For audit purpose, I think it is better to set the operator as the authorized appid.

2. In addition to OpenApi verification, userid is not verified in other places, such as the history publishing interface, users who exist will add DisplayName, and users who do not exist will directly display userid.
3. In this scenario of OpenApi, the system unavailability due to the departure of personnel should be a universal problem.

**Comment by nobodyiam** [comment]
> OpenApi is not user-authorized, and OpenApi can set any userid, even if the userid does not have the privilege of the project at all. For audit purpose, I think it is better to set the operator as the authorized appid.

I agree with you, besides I think for the open API scenario, the change history should display as something like `some-app-id on behalf of some-user-id`? If we could do that, I think we could skip user id check for open API scenarios.

**Comment by nobodyiam** [comment]
> ![](https://user-images.githubusercontent.com/18591662/156304348-dd71b581-b8f7-41ab-940d-0cf4f3bdcf71.png)

This is a compatible design when the user id doesn't exist in the system.

> the change history should display as something like `some-app-id on behalf of some-user-id`

What I mean by this is whether we could display the caller app as well as the operator user id for open API scenarios, which should reflect the actual behavior. If we don't display the caller app, then I think we still need to check the operator user id validity to make sure the data is clean.
