### ISSUE TITLE
运行过程中SpringValueRegistry.scanAndClean一直报NullPointerException

### ISSUE THREAD

**Issue by Ant-dong** [apolloconfig/apollo#4355]
java.lang.NullPointerException
 at java.util.Objects.requireNonNull(Objects.java:203)
 at com.google.common.collect.LinkedListMultimap.removeNode(LinkedListMultimap.java:300)
 at com.google.common.collect.LinkedListMultimap.access$300(LinkedListMultimap.java:101)
 at com.google.common.collect.LinkedListMultimap$NodeIterator.remove(LinkedListMultimap.java:386)
 at com.ctrip.framework.apollo.spring.property.SpringValueRegistry.scanAndClean(SpringValueRegistry.java:92)
 at com.ctrip.framework.apollo.spring.property.SpringValueRegistry.access$000(SpringValueRegistry.java:36)
 at com.ctrip.framework.apollo.spring.property.SpringValueRegistry$1.run(SpringValueRegistry.java:75)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:750)

version:1.9.1

**Comment by nobodyiam** [comment]
This looks like a bug, would you please help to provide the duplication scenario?

**Comment by Ant-dong** [comment]
> This looks like a bug, would you please help to provide the duplication scenario?

看其他的issue 我们自身怀疑是原型bean下注入apollo配置导致的这个问题 还需要提供什么？

**Comment by nobodyiam** [comment]
I'm not sure what's the actual scenario that caused this issue as the `prototype` bean case should have been tested before. So it would help a lot if you could help to provide a duplication scenario.

**Comment by Ant-dong** [comment]
> I'm not sure what's the actual scenario that caused this issue as the `prototype` bean case should have been tested before. So it would help a lot if you could help to provide a duplication scenario.
最近我们会修改成单例bean 我到时看看是否会出现这个问题 场景的话目前只是猜测是原型bean中导致的 具体的也不是很清楚是什么导致的

**Comment by nobodyiam** [comment]
fixed in https://github.com/apolloconfig/apollo-java/pull/95
