### ISSUE TITLE
scanAndClean方法中会导致程序会一只报错说LinkedListMultimap的size为负数的异常

### ISSUE THREAD

**Issue by Ant-dong** [apolloconfig/apollo#4356]
java.lang.IllegalArgumentException: negative size: -436
 at com.google.common.base.Preconditions.badPositionIndex(Preconditions.java:1409)
 at com.google.common.base.Preconditions.checkPositionIndex(Preconditions.java:1400)
 at com.google.common.base.Preconditions.checkPositionIndex(Preconditions.java:1382)
 at com.google.common.collect.LinkedListMultimap$NodeIterator.<init>(LinkedListMultimap.java:335)
 at com.google.common.collect.LinkedListMultimap$1EntriesImpl.listIterator(LinkedListMultimap.java:837)
 at java.util.AbstractList.listIterator(AbstractList.java:299)
 at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:239)
 at com.google.common.collect.Synchronized$SynchronizedCollection.iterator(Synchronized.java:179)
 at com.ctrip.framework.apollo.spring.property.SpringValueRegistry.scanAndClean(SpringValueRegistry.java:87)
 at com.ctrip.framework.apollo.spring.property.SpringValueRegistry.access$000(SpringValueRegistry.java:36)
 at com.ctrip.framework.apollo.spring.property.SpringValueRegistry$1.run(SpringValueRegistry.java:75)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:750)

version:1.9.1

**Comment by nisiyong** [comment]
Could you provide more details or some reproduce steps?

**Comment by Ant-dong** [comment]
> Could you provide more details or some reproduce steps?

原型bean中注入apollo配置，并发的情况下就会出现这个报错 还需要提供什么吗？
