### ISSUE TITLE
com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by jiangxiaoqiang** [apolloconfig/apollo#4376]
**描述bug**

在Kubernetes 1.15集群中部署apollo，启动config server时提示错误：

```
2022-05-24 21:36:10.268 ERROR 24 --- [cluster.local-7] c.n.e.cluster.ReplicationTaskProcessor   : It seems to be a socket read timeout exception, it will retry later. if it continues to happen and some eureka node occupied all the cpu time, you should set property 'eureka.server.peer-node-read-timeout-ms' to a bigger value

com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.netflix.eureka.cluster.DynamicGZIPContentEncodingFilter.handle(DynamicGZIPContentEncodingFilter.java:48)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
	at com.netflix.eureka.transport.JerseyReplicationClient.submitBatchUpdates(JerseyReplicationClient.java:116)
	at com.netflix.eureka.cluster.ReplicationTaskProcessor.process(ReplicationTaskProcessor.java:80)
	at com.netflix.eureka.util.batcher.TaskExecutors$BatchWorkerRunnable.run(TaskExecutors.java:187)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:278)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)

```

### 额外的细节和日志

- 版本：apollo-config-server:v1.0.0

这个是19年自己手动打包的docker镜像。平稳运行了3年多，最近遇到这个问题。搞了2个夜晚，毫无头绪。ConfigMap配置：

```
eureka.instance.preferIpAddress=true
eureka.server.peer-node-read-timeout-ms=120000
spring.datasource.url = jdbc:mysql://apollo-mysql.dabai-fat.svc.cluster.local:3306/ApolloConfigDBDEV?characterEncoding=utf8
spring.datasource.username = root
spring.datasource.password = gl4LucnXwLeLsw29QqJn4
eureka.service.url = http://service-apollo-meta-server-dev.sre.svc.cluster.local:8080/eureka/

```

 尝试登录到Pod里通过如下命令访问eureka：

`curl http://127.0.0.1:8080/eureka
`

确实无法访问。不过http://127.0.0.1:8080/是可以访问的。

**Comment by nobodyiam** [comment]
`Read timed out` normally means the server is slow to respond. If it only occurs occasionally and the meta server returns the correct data(/services/config, /services/admin), I think it's not a problem.
But you could check the server status, e.g. cpu/mem/gc, etc.
