### ISSUE TITLE
Long polling failed

### ISSUE THREAD

**Issue by louchenhui** [apolloconfig/apollo#4497]
2022-08-01 16:20:04,607 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 120 seconds. appId: http-server, cluster: default, namespaces: application reason: Could not complete get operation [Cause: Read timed out]

使用的是k8s环境，apollo-configservice-1.9.2.jar版本，测试和线上环境一直报这个错误，但是正常服务端有配置更新的话可以直接返回，请帮忙看下是什么问题。

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/16189939/182109947-d2749612-9e54-40a0-b1bf-aab65df381fb.png">

每一次之间相隔的时间是120秒（重试间隔） + 90s（客户端超时时间），看起来服务端60s超时时间并没有生效，排查不出来原因，

附：原始日志
2022-07-18 16:37:14,050 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 1 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:38:45,154 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 2 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:40:17,255 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 4 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:41:51,319 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 8 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:43:29,368 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 16 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:45:15,431 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 32 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:47:17,485 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 64 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:49:51,534 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 120 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:53:21,586 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 120 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 16:56:51,644 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 120 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]
2022-07-18 17:00:21,807 [Apollo-RemoteConfigLongPollService-1] WARN  c.c.f.a.i.RemoteConfigLongPollService [RemoteConfigLongPollService.java:213] - Long polling failed, will retry in 120 seconds. appId: grpc-server, cluster: default, namespaces: application, long polling url: http://xxx/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D, reason: Could not complete get operation [Cause: Read timed out]

**Comment by nobodyiam** [comment]
The server side should return in 60 seconds, would you please check the server logs to see if there is anything wrong?
And for the URL `http://xxx/`, what is the value of `xxx`? Is it the actual ip of the apollo-configservice?

**Comment by louchenhui** [comment]
@nobodyiam ，for the URL http://xxx/, xxx是内网域名，通过ingress网关配置的。下边是一些服务端的日志，从我自己的分析来看，感觉spring mvc这一层都返回了正确的结果-304，但是tomcat层可能没有处理成功。但这块打印的都是debug日志，不知道对tomcat最终的返回结果会不会有影响。
附：原始日志


2022-08-02 11:11:13.378 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.catalina.core.AsyncContextImpl  : Req: 13c1059a  CReq: 3416e5c2  RP:134583ef  Stage: 3  Thread: ttp-nio-8080-exec-10  State:                  N/A  Method: intDispatch  URI: /config/notifications/v2?cluster=default&appId=http-server&ip=172.16.6.124&notifications=%5B%7B%22namespaceName%22%3A%22messages_zh_tw.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22message_en_us.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22messages_zh_cn.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22messages_en_us.properties%22%2C%22notificationId%22%3A-1%7D%5D

org.apache.catalina.core.AsyncContextImpl$DebugException: null
        at org.apache.catalina.core.AsyncContextImpl.logDebug(AsyncContextImpl.java:512)
        at org.apache.catalina.core.AsyncContextImpl.doInternalDispatch(AsyncContextImpl.java:349)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:235)
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

2022-08-02 11:11:13.378 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.catalina.core.StandardWrapper   :   Returning non-STM instance
2022-08-02 11:11:13.379 TRACE 1 --- [http-nio-8080-exec-10] o.s.web.servlet.DispatcherServlet        : "ASYNC" dispatch for GET "/config/notifications/v2?cluster=default&appId=http-server&ip=172.16.6.124&notifications=%5B%7B%22namespaceName%22%3A%22messages_zh_tw.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22message_en_us.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22messages_zh_cn.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22messages_en_us.properties%22%2C%22notificationId%22%3A-1%7D%5D", parameters={masked}, headers={masked} in DispatcherServlet 'dispatcherServlet'
2022-08-02 11:11:13.379 TRACE 1 --- [http-nio-8080-exec-10] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to com.ctrip.framework.apollo.configservice.controller.NotificationControllerV2#pollNotification(String, String, String, String, String)
2022-08-02 11:11:13.379 TRACE 1 --- [http-nio-8080-exec-10] s.w.s.m.m.a.RequestMappingHandlerAdapter : Resume with async result [<304 NOT_MODIFIED Not Modified,[]>]
2022-08-02 11:11:13.379 TRACE 1 --- [http-nio-8080-exec-10] o.s.web.method.HandlerMethod             : Arguments: []
2022-08-02 11:11:13.379 DEBUG 1 --- [http-nio-8080-exec-10] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Using 'application/json;q=.2', given [text/html, image/gif, image/jpeg, */*;q=.2, */*;q=.2] and supported [application/json, application/*+json]
2022-08-02 11:11:13.379 DEBUG 1 --- [http-nio-8080-exec-10] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Nothing to write: null body
2022-08-02 11:11:13.379 TRACE 1 --- [http-nio-8080-exec-10] o.s.web.servlet.DispatcherServlet        : No view rendering, null ModelAndView returned.
2022-08-02 11:11:13.379 DEBUG 1 --- [http-nio-8080-exec-10] o.s.web.servlet.DispatcherServlet        : Exiting from "ASYNC" dispatch, status 304, headers={masked}
2022-08-02 11:11:13.379 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.catalina.core.AsyncContextImpl  : Firing onComplete() event for any AsyncListeners
2022-08-02 11:11:13.379 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.catalina.core.AsyncContextImpl  : Req: 13c1059a  CReq: 3416e5c2  RP:134583ef  Stage: 3  Thread: ttp-nio-8080-exec-10  State:                  N/A  Method: recycle      URI: /config/notifications/v2?cluster=default&appId=http-server&ip=172.16.6.124&notifications=%5B%7B%22namespaceName%22%3A%22messages_zh_tw.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22message_en_us.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22messages_zh_cn.properties%22%2C%22notificationId%22%3A-1%7D%2C%7B%22namespaceName%22%3A%22messages_en_us.properties%22%2C%22notificationId%22%3A-1%7D%5D

org.apache.catalina.core.AsyncContextImpl$DebugException: null
        at org.apache.catalina.core.AsyncContextImpl.logDebug(AsyncContextImpl.java:512)
        at org.apache.catalina.core.AsyncContextImpl.recycle(AsyncContextImpl.java:286)
        at org.apache.catalina.connector.Request.recycle(Request.java:531)
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:291)
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

2022-08-02 11:11:13.379 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@65cb5b1f:org.apache.tomcat.util.net.NioChannel@1c4cb8b8:java.nio.channels.SocketChannel[connected local=apollo-service-dev-apollo-configservice-v1-5b8b8499bb-ksn54/172.21.0.161:8080 remote=/172.21.0.235:36662]], Status in: [TIMEOUT], State out: [OPEN]
2022-08-02 11:11:13.380 DEBUG 1 --- [http-nio-8080-exec-10] o.a.coyote.http11.Http11InputBuffer      : Before fill(): [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position() [0]
2022-08-02 11:11:13.380 DEBUG 1 --- [http-nio-8080-exec-10] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@65cb5b1f:org.apache.tomcat.util.net.NioChannel@1c4cb8b8:java.nio.channels.SocketChannel[connected local=apollo-service-dev-apollo-configservice-v1-5b8b8499bb-ksn54/172.21.0.161:8080 remote=/172.21.0.235:36662]], Read from buffer: [0]
2022-08-02 11:11:13.380 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1231)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1141)
        at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:795)
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:359)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)
        at org.apache.coyote.AbstractProcessorLight.checkForPipelinedData(AbstractProcessorLight.java:108)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:60)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

2022-08-02 11:11:13.380 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.coyote.http11.Http11Processor   : Error state [CLOSE_CONNECTION_NOW]reported while processing request

java.io.EOFException: null
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1231)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1141)
        at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:795)
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:359)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)
        at org.apache.coyote.AbstractProcessorLight.checkForPipelinedData(AbstractProcessorLight.java:108)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:60)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

2022-08-02 11:11:13.380 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@65cb5b1f:org.apache.tomcat.util.net.NioChannel@1c4cb8b8:java.nio.channels.SocketChannel[connected local=apollo-service-dev-apollo-configservice-v1-5b8b8499bb-ksn54/172.21.0.161:8080 remote=/172.21.0.235:36662]], Status in: [TIMEOUT], State out: [CLOSED]
2022-08-02 11:11:13.380 DEBUG 1 --- [http-nio-8080-exec-10] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-8080-exec-10] latch=5

**Comment by nobodyiam** [comment]
估计是 ingress网关 的配置问题，可以用实际的 ip 访问看看

http://{real_ip}/config/notifications/v2?cluster=default&appId=grpc-server&ip=172.16.6.143&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A102%7D%5D

**Comment by louchenhui** [comment]
@nobodyiam 我们改了一下ingress nginx的超时设置，改成90s之后，客户端就可以直接返回了，这块默认应该60s，然后ingress这一层可能有重试的机制，所以导致客户端在90s会自动超时。具体的机制我们在研究一下，多谢您的回复～
