### ISSUE TITLE
Exception occurred when publish/rollback namespaces with gray release

### ISSUE THREAD

**Issue by nobodyiam** [apolloconfig/apollo#4563]
- [x] I have checked the [discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] I have searched the [issues](https://github.com/ctripcorp/apollo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase) of this repository and believe that this is not a duplicate.

**Describe the bug**

When publish/rollback namespaces with gray release, the operation failed with the error message `java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 20 path $.`.

The stacktrace in server log is as follows:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was NUMBER at line 1 column 20 path $.
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.ctrip.framework.apollo.biz.service.ReleaseService.getBranchReleaseKeys(ReleaseService.java:333)
```

**To Reproduce**
1. Create a grayscale version for some namespace, e.g. `application`
2. Change some value in the grayscale version and publish the grayscale version
3. Change some value in the main version
4. Publish or rollback the main version, then you will see the error

**Expected behavior**
The publish/rollback operations should work with no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/837658/189526239-25569d09-1755-4c71-b248-27387f7f8ac2.png)

### Additional Details & Logs

- Version: 2.1.0-SNAPSHOT

**Comment by nobodyiam** [comment]
It seesm related to #4502
