### ISSUE TITLE
邮件通知发送失败（需要使用ssl 465端口）

### ISSUE THREAD

**Issue by zhukangfeng** [apolloconfig/apollo#4601]
**邮件 SMTP 服务配置，采用 25 端口，发送失败**

公司内部邮箱 SMTP 服务，要求必须采用 SMTP_SSL，所以采用的端口是 465。apollo 配置中心采用的端口是 25，所以报连接错误。

**复现**

通过如下步骤可以复现：

1. 选择只能通过 SSL 连接的邮箱
2. 配置 SMTP 信息，并开启邮件通知。
3. 修改配置，查看错误日志

**期望**

希望用户可以选择邮箱通知的协议，允许采用 SMTP_SSL 的方式发送邮件通知。
比如增加配置：`email.config.ssl` 设置为 `true`; 则采用 SMTP_SSL 方式连接 465 端口

### 额外的细节和日志

- 版本：2.0.1
- 错误日志
```
ERROR 1 --- [Apollo-ConfigPublishNotify-1] c.c.f.a.p.s.d.DefaultEmailService        : send email failed.                    
                                                                                                                                                    
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: xxxx.xxxx.com, 25; timeout -1                                            
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209)                                                                      
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)                                                                  
        at javax.mail.Service.connect(Service.java:366)                                                                                             
        at javax.mail.Service.connect(Service.java:246)                                                                                             
        at com.ctrip.framework.apollo.portal.spi.defaultimpl.DefaultEmailService.send(DefaultEmailService.java:68)                                  
        at com.ctrip.framework.apollo.portal.listener.ConfigPublishListener$ConfigPublishNotifyTask.sendPublishEmail(ConfigPublishListener.java:164)
        at com.ctrip.framework.apollo.portal.listener.ConfigPublishListener$ConfigPublishNotifyTask.run(ConfigPublishListener.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)            
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)    
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)    
        at java.lang.Thread.run(Thread.java:748)                                              
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)              
        at java.net.PlainSocketImpl.socketConnect(Native Method)               
```

**Comment by nobodyiam** [comment]
Have you tried to set system properties like `mail.smtp.port` and `mail.smtp.socketFactory.class`, see https://www.geeksforgeeks.org/sending-email-java-ssltls-authentication/

**Comment by zhukangfeng** [comment]
> 

直接把这两个变量设置成 apollo 配置中心的配置项，是不会生效的。
你这个方案似乎得自己写 EmailService.java; `DefaultEmailService.java` 代码中，没有支持这两个参数传入。

个人感觉，最简单的是， 默认邮件发送 `DefaultEmailService.java` 中就支持 ssl，用户只需要在配置项中设定是否用 ssl 发送。

**Comment by nobodyiam** [comment]
I haven't tried it but it looks like [the code](https://github.com/apolloconfig/apollo/blob/master/apollo-portal/src/main/java/com/ctrip/framework/apollo/portal/spi/defaultimpl/DefaultEmailService.java#L54) would use system properties to init the email session.
