### ISSUE TITLE
数据库隔离级别设置成读已提交 ，则页面创建APP会失败。

### ISSUE THREAD

**Issue by Tangjinquan** [apolloconfig/apollo#4619]
数据库隔离级别设置为读已提交，会造成页面创建应用失败。

**描述bug**

com.ctrip.framework.apollo.portal.spi.defaultimpl.DefaultRoleInitializationService#initAppRoles  方法内部 出现问题

**复现**

通过如下步骤可以复现：

1. 本地启动
2. 创建应用
3.  rolePermissionService.assignRoleToUsers 判断条件失败 。
4.  因为前面有创建的role角色 ，在这里 rolePermissionService.assignRoleToUsers 并没有查出来 。
5. 如果我设置成数据库为RR级别 ，就可以查出来 。

**期望**

希望能正常创建

**截图**

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/28834338/198543393-ebba8741-04df-4625-8e79-66a9aed2c7b7.png">

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/28834338/198543554-8559f566-d4c4-44e5-ac9c-74ebc4bc31d4.png">

**Comment by Tangjinquan** [comment]
堆栈信息
2022-10-28 16:36:45.244 ERROR 98406 --- [p-nio-80-exec-1] .c.f.a.c.c.GlobalDefaultExceptionHandler : Role Master+viatris111 doesn't exist!

java.lang.IllegalStateException: Role Master+viatris111 doesn't exist!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
	at com.ctrip.framework.apollo.portal.spi.defaultimpl.DefaultRolePermissionService.assignRoleToUsers(DefaultRolePermissionService.java:141)
	at com.ctrip.framework.apollo.portal.spi.defaultimpl.DefaultRolePermissionService$$FastClassBySpringCGLIB$$6b28c3a4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
