### ISSUE TITLE
Apollo2.0.1版本本地启动报错

### ISSUE THREAD

**Issue by zhoushuai1119** [apolloconfig/apollo#4621]
Apollo Version：2.0.1

本地启动ApolloApplication报错，相关配置如下：
![image](https://user-images.githubusercontent.com/29701159/199194694-c1b017ee-960c-4376-8811-54afa772b36b.png)
![image](https://user-images.githubusercontent.com/29701159/199194734-91520974-9539-44ea-ada7-5a26ee652876.png)

错误信息如下：
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jmxMBeanExporter' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/jmx/JmxEndpointAutoConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jmx.export.MBeanExportException: Failed to register MBean for endpoint 'beans'; nested exception is javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Endpoint,name=Beans,context=63998bf4
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
	at com.ctrip.framework.apollo.assembly.ApolloApplication.main(ApolloApplication.java:63)
Caused by: org.springframework.jmx.export.MBeanExportException: Failed to register MBean for endpoint 'beans'; nested exception is javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Endpoint,name=Beans,context=63998bf4
	at org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter.register(JmxEndpointExporter.java:105)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter.register(JmxEndpointExporter.java:90)
	at org.springframework.boot.actuate.endpoint.jmx.JmxEndpointExporter.afterPropertiesSet(JmxEndpointExporter.java:81)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 15 common frames omitted
Caused by: javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Endpoint,name=Beans,context=63998bf4
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
`

**Comment by mghio** [comment]
`Disable JMX agent` for the IntelliJ build run.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/43461943/199265814-5b391e19-4da2-4506-82e6-60dfcc15a3fb.png">

**Comment by zhoushuai1119** [comment]
可以了，谢谢
