### ISSUE TITLE
apollo对接OIDC必须是https吗

### ISSUE THREAD

**Issue by chenke3** [apolloconfig/apollo#4783]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

按照文档配置OIDC对接，但是OIDC提供的url是非https的，项目启动报错
异常如下：
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/servlet/OAuth2ClientRegistrationRepositoryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalStateException: The Issuer "http://xxx.xxxx.xxx:38776/" provided in the configuration metadata did not match the requested issuer "http://xxx.xxxx.xxx:38776/public/api/application/plugin_oidc/oidc"
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalStateException: The Issuer "http://10.211.96.22:38776/" provided in the configuration metadata did not match the requested issuer "http://10.211.96.22:38776/public/api/application/plugin_oidc/oidc"
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 33 common frames omitted
Caused by: java.lang.IllegalStateException: The Issuer "http://xx.xxx.xx.xx:38776/" provided in the configuration metadata did not match the requested issuer "http://xx.xxx.xx.xx:38776/public/api/application/plugin_oidc/oidc"
	at org.springframework.util.Assert.state(Assert.java:97)
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.withProviderConfiguration(ClientRegistrations.java:238)
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.lambda$oidc$0(ClientRegistrations.java:157)
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:208)
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.fromIssuerLocation(ClientRegistrations.java:144)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getBuilderFromIssuerIfPossible(OAuth2ClientPropertiesRegistrationAdapter.java:83)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistration(OAuth2ClientPropertiesRegistrationAdapter.java:59)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.lambda$getClientRegistrations$0(OAuth2ClientPropertiesRegistrationAdapter.java:53)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistrations(OAuth2ClientPropertiesRegistrationAdapter.java:52)
	at org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientRegistrationRepositoryConfiguration.clientRegistrationRepository(OAuth2ClientRegistrationRepositoryConfiguration.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

希望看下是什么原因，是否是因为不支持https导致

**截图**
<img width="952" alt="image" src="https://user-images.githubusercontent.com/25950559/223896641-ca41d001-93ad-4131-aa1f-7d4024b3eed4.png">
### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
I'm not an expert in oidc but the message `The Issuer "http://xx.xxx.xx.xx:38776/" provided in the configuration metadata did not match the requested issuer "http://xx.xxx.xx.xx:38776/public/api/application/plugin_oidc/oidc"` seems not related to https.

**Comment by chenke3** [comment]
> 

是的，和这个无关，我异常日志贴的不对，但是我想了解下，是否必须是https？

**Comment by chenke3** [comment]
> I'm not an expert in oidc but the message `The Issuer "http://xx.xxx.xx.xx:38776/" provided in the configuration metadata did not match the requested issuer "http://xx.xxx.xx.xx:38776/public/api/application/plugin_oidc/oidc"` seems not related to https.

顺便提个问题，我这样配置是否可以
server:
  # 解析反向代理请求头
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      client:
        provider:
          paasportal:
            oidcUrl: http://1.1.1.1:38776/public/api/application/plugin_oidc/oidc
            authorization-uri: ${spring.security.oauth2.client.provider.paasportal.oidcUrl}/authorize
            token-uri: ${spring.security.oauth2.client.provider.paasportal.oidcUrl}/token
            user-info-uri: ${spring.security.oauth2.client.provider.paasportal.oidcUrl}/user_info
            jwk-set-uri: ${spring.security.oauth2.client.provider.paasportal.oidcUrl}/jwks
            user-name-attribute: displayname
#            issuer-uri: http://1.1.1.1:38776/public/api/application/plugin_oidc/oidc
        registration:
          paasportal:
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            client-id: LrX0Wj1btuU8jacT3u4sN44O
            provider: paasportal
            scope:
              - openid
            client-secret: 7vaVY5ltoFbLZgDPqxhZ0LqP
            redirect-uri: http://127.0.0.1:8070

**Comment by nobodyiam** [comment]
according to the [oidc guide](https://www.apolloconfig.com/#/en/development/portal-how-to-implement-user-login-function?id=implementation-3-access-to-oidc), it needs to be https.

![image](https://user-images.githubusercontent.com/837658/224457185-28bc02bf-3957-4b40-95b2-65cd368d8fd3.png)

**Comment by chenke3** [comment]
是否有技术支持的群，关于OIDC的对接，有一些问题想要进群咨询
