### ISSUE TITLE
SpringValueRegistry中throw ConcurrentModificationException

### ISSUE THREAD

**Issue by zhangmingjava** [apolloconfig/apollo#4800]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

java.util.ConcurrentModificationException
	at com.google.common.collect.LinkedListMultimap$NodeIterator.checkForConcurrentModification(LinkedListMultimap.java:345)
	at com.google.common.collect.LinkedListMultimap$NodeIterator.hasNext(LinkedListMultimap.java:351)
	at com.ctrip.framework.apollo.spring.property.SpringValueRegistry.scanAndClean(SpringValueRegistry.java:68)
	at com.ctrip.framework.apollo.spring.property.SpringValueRegistry.access$000(SpringValueRegistry.java:18)
	at com.ctrip.framework.apollo.spring.property.SpringValueRegistry$1.run(SpringValueRegistry.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**复现**

通过如下步骤可以复现：

1. springboot版本1.5.13.RELEASE,apollo-client版本 1.7.0
2. 启动项目抛出异常ConcurrentModificationException

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本： apollo-client 1.7.0
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Would you please help to submit a demo showing this issue?

**Comment by zhangmingjava** [comment]
启动项目时,有这个日志输出.怀疑是该应用配置内存过小,导致scanAndClean任务和put并发冲突导致的.

**Comment by nobodyiam** [comment]
As the `scanAndClean` will run periodically, we could ignore the `ConcurrentModificationException` safely.
We may need to add locks to the `register` and `scanAndClean` methods to avoid potential `ConcurrentModificationException`.

**Comment by huomengbo** [comment]
@nobodyiam 这个问题解决了吗，看代码还是之前的样子，我们这里也遇到了同样的问题，希望能快点修复
