### ISSUE TITLE
Could not find config for namespace - appId: 0010010001, cluster: default, namespace: application, please check whether the configs are released in Apollo!]

### ISSUE THREAD

**Issue by jiangxiaoqiang** [apolloconfig/apollo#4806]
- [ ] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ ] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ ] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

提示找不到命名空间，application命名空间是初始状态，没有任何配置，现在用的是application-yaml命名空间。application命名空间必须要的吗？需要发布吗？可以移除application命名空间吗？为什么还需要application命名空间？

```
[13:23:40:158] [WARN] - com.ctrip.framework.apollo.internals.AbstractConfigRepository.trySync(AbstractConfigRepository.java:29) - Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: 0010010001, cluster: default, namespace: application, url: http://192.168.10.93:8080/configs/0010010001/default/application?ip=192.168.10.93 [Cause: [status code: 404] Could not find config for namespace - appId: 0010010001, cluster: default, namespace: application, please check whether the configs are released in Apollo!]
[13:24:00:882] [WARN] - io.netty.channel.ChannelInitializer.exceptionCaught(ChannelInitializer.java:97) - Failed to initialize a channel. Closing: [id: 0x5080f025, L:/192.168.10.93:58080 - R:/192.168.10.93:63059]
io.netty.channel.ChannelPipelineException: com.dolphin.soa.post.config.common.websocket.WebSocketHandler is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:600) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:202) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at com.dolphin.soa.post.config.common.websocket.WebSocketServer$1.initChannel(WebSocketServer.java:104) ~[main/:?]

```

**复现**

通过如下步骤可以复现：

1. 新建application-yaml命名空间
2. 调整配置使用application-yaml命名空间

```
# apollo namespaces
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled = true
apollo.bootstrap.namespaces = application-yaml.yaml

```

**期望**

直接用application-yaml命名空间

### 额外的细节和日志

- 版本：2.1.0
- 错误日志
- 配置：
- 平台和操作系统

**Comment by nobodyiam** [comment]
Did you mark the `@EnableApolloConfig`/`@ApolloConfig`/`@ApolloConfigChangeListener` somewhere? They will enable the default application namespace if no value is provided.

**Comment by jiangxiaoqiang** [comment]
I set the default value for the apollo annoatation and problem sovled, thank you.
