### ISSUE TITLE
No available admin server. Maybe because of meta server down or all admin server down

### ISSUE THREAD

**Issue by why11xulei** [apolloconfig/apollo#4834]
1.报错信息
2023-04-04 14:58:25.789 ERROR 52 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://10.20.3.231:8180

com.ctrip.framework.apollo.common.exception.ServiceException: No available admin server. Maybe because of meta server down or all admin server down. Meta server address: http://10.20.3.231:8180
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.getAdminServices(RetryableRestTemplate.java:212)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:116)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:82)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:27)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:132)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2023-04-04 14:58:25.789 ERROR 52 --- [HealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 1935, meta server address: http://10.20.3.231:8180

2.启动命令
docker run -d -p 8180:8180 --restart=always \
-e SPRING_DATASOURCE_URL="jdbc:mysql://10.20.3.231:3316/ApolloConfigDB?characterEncoding=utf8" \
-e SPRING_DATASOURCE_USERNAME=root \
-e SPRING_DATASOURCE_PASSWORD=root \
-e EUREKA_INSTANCE_IP_ADDRESS=10.20.3.231 \
-e SERVER_PORT=8180 \
--name apollo-configservice apolloconfig/apollo-configservice:1.7.1

docker run -d -p 8190:8190 --restart=always \
-e SPRING_DATASOURCE_URL="jdbc:mysql://10.20.3.231:3316/ApolloConfigDB?characterEncoding=utf8" \
-e SPRING_DATASOURCE_USERNAME=root \
-e SPRING_DATASOURCE_PASSWORD=root  \
-e EUREKA_INSTANCE_IP_ADDRESS=10.20.3.231 \
-e SERVER_PORT=8190 \
--name apollo-adminservice apolloconfig/apollo-adminservice:1.7.1

docker run -d -p 8170:8170 --restart=always \
-e SPRING_DATASOURCE_URL="jdbc:mysql://10.20.3.231:3316/ApolloPortalDB?characterEncoding=utf8" \
-e SPRING_DATASOURCE_USERNAME=root \
-e SPRING_DATASOURCE_PASSWORD=root \
-e APOLLO_PORTAL_ENVS=dev \
-e SERVER_PORT=8170 \
-e DEV_META=http://10.20.3.231:8180,http://10.20.3.232:8180,http://10.20.3.233:8180 \
--name apollo-portal apolloconfig/apollo-portal:1.7.1

3.情况
1）访问http://10.20.3.231:8180/
  Application处显示No instances available
2）访问http://10.20.3.231:8180/services/admin，返回[]

**Comment by nobodyiam** [comment]
see [2.1.3 Adjusting server-side configuration](https://www.apolloconfig.com/#/en/deployment/distributed-deployment-guide?id=_213-adjusting-server-side-configuration)

![image](https://user-images.githubusercontent.com/837658/230029177-9e1780cb-5830-4219-b41e-62d43d53675b.png)

**Comment by why11xulei** [comment]
![image](https://user-images.githubusercontent.com/45457541/230251085-79f254e1-5492-4c98-af7c-30bcbd607c94.png)
![image](https://user-images.githubusercontent.com/45457541/230251120-c1815cdc-b670-4904-86d0-51f571eed07c.png)
Looks like there's no problem

**Comment by nobodyiam** [comment]
you may check the config/admin service logs then.
