### ISSUE TITLE
无法加载实例ConfigRegistry

### ISSUE THREAD

**Issue by love720720** [apolloconfig/apollo#4845]
java.lang.IllegalStateException: This is a proxy used to support circular references. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:36)
	at com.sun.proxy.$Proxy12.getConfig(Unknown Source)
	at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
	at com.wtyt.jars.logger.commons.toolkits.ApolloToolkit.getApolloValue(ApolloToolkit.java:49)
	at com.wtyt.jars.logger.commons.toolkits.ApolloToolkit.getApolloValue(ApolloToolkit.java:62)
	at com.wtyt.jars.logger.commons.toolkits.ConfigToolkit.getLog4j2Config(ConfigToolkit.java:17)
	at com.wtyt.jars.logger.factory.LugeLog4j2ConfigurationFactory.createConfiguration(LugeLog4j2ConfigurationFactory.java:36)
	at com.wtyt.jars.logger.factory.LugeLog4j2ConfigurationFactory.getConfiguration(LugeLog4j2ConfigurationFactory.java:188)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:437)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:325)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:690)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:55)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at com.ctrip.framework.apollo.spi.DefaultConfigRegistry.<clinit>(DefaultConfigRegistry.java:14)
	at com.ctrip.framework.apollo.spi.DefaultConfigRegistry$$FastClassByGuice$$35dae462.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38)
	at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
	at com.ctrip.framework.apollo.spi.DefaultConfigFactoryManager.<init>(DefaultConfigFactoryManager.java:17)
	at com.ctrip.framework.apollo.spi.DefaultConfigFactoryManager$$FastClassByGuice$$9f875ba8.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38)
	at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
	at com.ctrip.framework.apollo.internals.DefaultConfigManager.<init>(DefaultConfigManager.java:23)
	at com.ctrip.framework.apollo.internals.DefaultConfigManager$$FastClassByGuice$$dcce707e.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38)
	at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
	at com.ctrip.framework.apollo.ConfigService.getManager(ConfigService.java:25)
	at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
	at com.ctrip.framework.apollo.ConfigService.getAppConfig(ConfigService.java:51)
	at com.wtyt.util.apollo.ApolloPropertyPlaceholderConfigurer.postProcessBeanFactory(ApolloPropertyPlaceholderConfigurer.java:28)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:553)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:527)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:362)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:255)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:199)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:45)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4697)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5163)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1719)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:479)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:428)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
12-Apr-2023 09:44:14.855 ���� [RMI TCP Connection(2)-127.0.0.1] org.springframework.web.context.ContextLoader.initWebApplicationContext Context initialization failed
	com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.internals.ConfigManager!
		at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:38)
		at com.ctrip.framework.apollo.ConfigService.getManager(ConfigService.java:25)
		at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
		at com.ctrip.framework.apollo.ConfigService.getAppConfig(ConfigService.java:51)
		at com.wtyt.util.apollo.ApolloPropertyPlaceholderConfigurer.postProcessBeanFactory(ApolloPropertyPlaceholderConfigurer.java:28)
		at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:553)
		at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:527)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:362)
		at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:255)
		at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:199)
		at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:45)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4697)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5163)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1719)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:479)
		at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:428)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:286)
		at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
		at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
		at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
		at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
		at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
		at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
		at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
		at sun.rmi.transport.Transport$1.run(Transport.java:200)
		at sun.rmi.transport.Transport$1.run(Transport.java:197)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
		at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for com.ctrip.framework.apollo.internals.ConfigManager!
		at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:42)
		at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
		... 57 more
	Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.spi.ConfigFactoryManager!
  at com.ctrip.framework.apollo.internals.DefaultConfigManager.<init>(DefaultConfigManager.java:22)
  while locating com.ctrip.framework.apollo.internals.DefaultConfigManager
  at com.ctrip.framework.apollo.internals.DefaultInjector$ApolloModule.configure(DefaultInjector.java:55)
  while locating com.ctrip.framework.apollo.internals.ConfigManager

1 error
		at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
		at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
		at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38)
		... 58 more
	Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.spi.ConfigFactoryManager!
		at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:38)
		at com.ctrip.framework.apollo.internals.DefaultConfigManager.<init>(DefaultConfigManager.java:23)
		at com.ctrip.framework.apollo.internals.DefaultConfigManager$$FastClassByGuice$$dcce707e.newInstance(<generated>)
		at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
		at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
		at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
		at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
		at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
		at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
		at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
		at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
		at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
		at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
		at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
		at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
		at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
		... 60 more
	Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for com.ctrip.framework.apollo.spi.ConfigFactoryManager!
		at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:42)
		at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
		... 75 more
	Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.spi.ConfigRegistry!
  at com.ctrip.framework.apollo.spi.DefaultConfigFactoryManager.<init>(DefaultConfigFactoryManager.java:16)
  while locating com.ctrip.framework.apollo.spi.DefaultConfigFactoryManager
  at com.ctrip.framework.apollo.internals.DefaultInjector$ApolloModule.configure(DefaultInjector.java:56)
  while locating com.ctrip.framework.apollo.spi.ConfigFactoryManager

1 error
		at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
		at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
		at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38)
		... 76 more
	Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for type com.ctrip.framework.apollo.spi.ConfigRegistry!
		at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:38)
		at com.ctrip.framework.apollo.spi.DefaultConfigFactoryManager.<init>(DefaultConfigFactoryManager.java:17)
		at com.ctrip.framework.apollo.spi.DefaultConfigFactoryManager$$FastClassByGuice$$9f875ba8.newInstance(<generated>)
		at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
		at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
		at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
		at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
		at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
		at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
		at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
		at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
		at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
		at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
		at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
		at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
		at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
		... 78 more
	Caused by: com.ctrip.framework.apollo.exceptions.ApolloConfigException: Unable to load instance for com.ctrip.framework.apollo.spi.ConfigRegistry!
		at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:42)
		at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
		... 93 more
	Caused by: java.lang.ExceptionInInitializerError
		at com.ctrip.framework.apollo.spi.DefaultConfigRegistry$$FastClassByGuice$$35dae462.newInstance(<generated>)
		at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
		at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
		at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
		at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
		at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
		at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
		at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
		at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
		at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
		at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
		at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
		at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
		at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
		at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
		at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38)
		... 94 more
		
		
入口log4j2.component.properties log4j2.ConfigurationFactory

**Comment by nobodyiam** [comment]
Looks like circular dependency issue, would you please submit a demo to reproduce this issue?

**Comment by love720720** [comment]
> Looks like circular dependency issue, would you please submit a demo to reproduce this issue?

Attempted to solve the problem through OpenAPI and suddenly found that the problem can be easily solved by adding the package [com.ctrip.frameworkapollo;apollo-openapi:2.1.0].

**Comment by nobodyiam** [comment]
> > Looks like circular dependency issue, would you please submit a demo to reproduce this issue?
> 
> Attempted to solve the problem through OpenAPI and suddenly found that the problem can be easily solved by adding the package [com.ctrip.frameworkapollo;apollo-openapi:2.1.0].

Simply adding the openapi dependency and with no code change?

**Comment by love720720** [comment]
> > > Looks like circular dependency issue, would you please submit a demo to reproduce this issue?
> > 
> > 
> > Attempted to solve the problem through OpenAPI and suddenly found that the problem can be easily solved by adding the package [com.ctrip.frameworkapollo;apollo-openapi:2.1.0].
> 
> Simply adding the openapi dependency and with no code change?

Yes, the code has not been changed. The framework version is relatively low. If there is a chance, I will submit a sample project.

**Comment by nobodyiam** [comment]
You may use the latest version of apollo-client. If the issue still exists, you may submit a sample demo to reproduce this issue.
