### ISSUE TITLE
apollo注册到公网地址有问题

### ISSUE THREAD

**Issue by yuanhaishan** [apolloconfig/apollo#4871]
2023-05-12 19:39:01.849  WARN 1 --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: org.apache.http.conn.ConnectTimeoutException: Connect to 公网ip:58080 timed out
2023-05-12 19:39:01.849  WARN 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_APOLLO-CONFIGSERVICE/192.168.0.4:apollo-configservice:58080 - registration failed Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.DiscoveryClient.register(DiscoveryClient.java:876)
        at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:121)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2023-05-12 19:39:01.849  WARN 1 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : There was a problem with the instance info replicator

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
        at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.register(EurekaHttpClientDecorator.java:56)
        at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$1.execute(EurekaHttpClientDecorator.java:59)
        at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)

我使用docker部署了apollo的configservice跟adminservice，使用的是host模式，configservice的端口是58080，adminservice的端口是58090
```
运行时候也注册了公网的ip地址
-e eureka.instance.ip-address=公网ip地址
```

这个ip公网地址有点特殊  是nat网关地址  58080、58090也都授权了，就是注册不到euraka上面

**Comment by nobodyiam** [comment]
> 2023-05-12 19:39:01.849 WARN 1 --- [nfoReplicator-0] c.n.d.s.t.d.RetryableEurekaHttpClient : Request execution failed with message: org.apache.http.conn.ConnectTimeoutException: Connect to 公网ip:58080 timed out

看这个报错注册是 OK 的，只是连不上？

**Comment by yuanhaishan** [comment]
注册到公网上面有问题  这个公网地址是nat的公网地址  本机telnet 公网ip地址 58080、58090都不通  有没有什么解决方法

**Comment by nobodyiam** [comment]
客户端使用公网 ip 访问，服务端自身通过内网 ip 访问？
可以看看 [1.4.4 直接指定apollo-configservice地址](https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_144-%e7%9b%b4%e6%8e%a5%e6%8c%87%e5%ae%9aapollo-configservice%e5%9c%b0%e5%9d%80)

**Comment by yuanhaishan** [comment]
我的portal要将这个apollo接管过来，所以这个apollo需要注册到公网上面，现在注册不上去
