### ISSUE TITLE
oidc登录，升级到2.1.0版本 请求返回500

### ISSUE THREAD

**Issue by sourceliex** [apolloconfig/apollo#4872]
- [ x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [ x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [ x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

版本更新到2.1.0, 并且使用的是oidc登录， 访问portal返回500
![image](https://github.com/apolloconfig/apollo/assets/108520585/f3b152a5-1f2c-4968-a3d9-a8abbb384b35)

nested exception is java.lang.RuntimeException: Spring-session JSON deserializing error, This is usually caused by the system upgrade, please clear the browser cookies and try again.
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.deserialize(JdbcIndexedSessionRepository.java:628)
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.access$1900(JdbcIndexedSessionRepository.java:133)
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$SessionResultSetExtractor.lambda$extractData$0(JdbcIndexedSessionRepository.java:898)
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$4.get(JdbcIndexedSessionRepository.java:650)
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.getAttribute(JdbcIndexedSessionRepository.java:728)
	at org.springframework.session.PrincipalNameIndexResolver.resolveIndexValueFor(PrincipalNameIndexResolver.java:46)
	at org.springframework.session.SingleIndexResolver.resolveIndexesFor(SingleIndexResolver.java:48)
	at org.springframework.session.DelegatingIndexResolver.resolveIndexesFor(DelegatingIndexResolver.java:49)
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.lambda$save$11(JdbcIndexedSessionRepository.java:840)
	at org.springframework.transaction.support.TransactionOperations.lambda$executeWithoutResult$0(TransactionOperations.java:68)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.transaction.support.TransactionOperations.executeWithoutResult(TransactionOperations.java:67)
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.save(JdbcIndexedSessionRepository.java:837)
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.access$200(JdbcIndexedSessionRepository.java:665)

简洁明了地描述一下bug

**复现**

通过如下步骤可以复现：

1. 
2. 
3. 
4. 

**期望**

简介明了地描述你希望正常情况下应该发生什么

**截图**

如果可以，附上截图来描述你的问题

### 额外的细节和日志

- 版本：
- 错误日志
- 配置：
- 平台和操作系统

**Comment by sourceliex** [comment]
我尝试过以下操作，问题依旧.
1. 清除浏览器cookie
2. 清空表 SPRING_SESSION、SPRING_SESSION_ATTRIBUTES数据

版本迭代: 2.0.1  to  2.1.0

**Comment by Shelby-Jiao** [comment]
refer to https://github.com/apolloconfig/apollo/issues/4791, try this
`SPRING_SESSION_STORE_TYPE=none`
for a walkaround
