### ISSUE TITLE
K8S 启动apollo-configservice 报数据库错误

### ISSUE THREAD

**Issue by matrixfish** [apolloconfig/apollo#4896]
1、按照这个进行安装
https://www.apolloconfig.com/#/zh/deployment/distributed-deployment-guide?id=_24-kubernetes%e9%83%a8%e7%bd%b2

2、检查数据库正常，账号密码登
mysql> select `Id`, `Key`, `Value`, `Comment` from `ApolloConfigDB`.`ServerConfig` limit 1;
+----+--------------------+-------------------------------+------------------+
| Id | Key                | Value                         | Comment          |
+----+--------------------+-------------------------------+------------------+
|  1 | eureka.service.url | http://localhost:8080/eureka/ | EurekaUrlservice |
+----+--------------------+-------------------------------+------------------+
1 row in set (0.00 sec)

mysql> select `Id`, `Key`, `Value`, `Comment` from `ApolloPortalDB`.`ServerConfig` limit 1;
+----+--------------------+-------+---------+
| Id | Key                | Value | Comment |
+----+--------------------+-------+---------+
|  1 | apollo.portal.envs | dev   |         |
+----+--------------------+-------+---------+
1 row in set (0.00 sec)

3、value.yaml配置
`
configdb:
  name: apollo-configdb
  host: "10.43.23.47"
  port: 3306
  dbName: ApolloConfigDB
  userName: "root"
  password: "root"
  connectionStringProperties: characterEncoding=utf8&useSSL=false
  service:
    enabled: true
    fullNameOverride: ""
    port: 3306
    type: ClusterIP

`

4、IP地址是10.43.23.47，端口也正确
root@mounte:/work/xx/apollo# kubectl  --namespace infrastructure-thirdpart  get service
NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
apollo-mysql                              ClusterIP   10.43.23.47     <none>        3306/TCP   88m
apollo-mysql-headless                     ClusterIP   None            <none>        3306/TCP   88m

5、apollo-configservice报错：
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
	... 159 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)

**Comment by nobodyiam** [comment]
> Caused by: java.net.SocketTimeoutException: connect timed out

这个报错说明连不上数据库
