### ISSUE TITLE
配置文件加不了注释，提交报错是怎么回事

### ISSUE THREAD

**Issue by Fivemeters** [apolloconfig/apollo#4969]
![image](https://github.com/apolloconfig/apollo/assets/46667916/d328b7d2-5874-4069-a40d-f32f08f9639e)
Unknown column '0x' in 'field list'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 221 common frames omitted

**Comment by Fivemeters** [comment]
我创建了一个类型为properties的namespace，添加了个属性abc=123，然后添加了注释，如下：
#密码
adb=123
提交的时候就报错，如果我把#密码这个注释删掉的话，就能提交成功。
用的2.1.0这个版本。
还是properties类型的namespace不能有#这个特殊字符。

**Comment by nobodyiam** [comment]
在 [apollo-demo](http://81.68.181.139/) 站点是否可以复现？看上去可能是配置的问题

**Comment by Fivemeters** [comment]
> 在 [apollo-demo](http://81.68.181.139/) 站点是否可以复现？看上去可能是配置的问题

![image](https://github.com/apolloconfig/apollo/assets/46667916/e292f645-e079-4ad7-a655-9c78c4f91d94)
在这上面增加注释是可以的，是啥问题呢，我看了下commit表的字符集是utf8mb4_general_ci，这个站点的版本也是2.1.0的么。

**Comment by nobodyiam** [comment]
数据库连接串的配置可以检查一下，另外配置的值是中文试过吗？
