### ISSUE TITLE
apollo.meta; nested exception is java.net.UnknownHostException: apollo.meta

### ISSUE THREAD

**Issue by starsky20** [apolloconfig/apollo#5117]
1.我是基于最新的 master 分支 build 编译的，未改动服务端口地址。

2.根据官网说明，分别修改了configservice、adminservice数据库application-github.properties配置。通过idea 分别启动服务指定了激活环境 -Dapollo_profile=github,auth，configservice、adminservice启动正常，通过访问8080测试，eureka正常，两个服务健康状态正常。

3.修改了protal数据库serverconfig 配置 apollo.portal.envs=dev。apollo.portal.meta.servers={"dev":"http://192.168.3.174:8080"}

4.修改protalservice服务配置文件apollo-env.properties，只是配置了dev.meta=http://192.168.3.174:8080， 其他的全部注释了。
修改application-github.properties的数据库连接。启动服务时指定了激活环境-Dapollo_profile=github,auth,dev。

启动报错内容如下：
6912 --- [           main] .f.a.p.e.DefaultPortalMetaServerProvider : Loaded meta server addresses from system property, os environment and properties file: {DEV=http://192.168.3.174:8080}
2024-03-31 21:59:57.482  WARN 16912 --- [erviceLocator-1] c.c.f.a.p.e.PortalMetaDomainService      : Meta server address fallback to [http://apollo.meta] for env [FAT], because it is not available in MetaServerProvider
2024-03-31 21:59:57.611 ERROR 16912 --- [erviceLocator-1] c.c.f.a.p.c.AdminServiceAddressLocator   : Get admin server address from meta server failed. env: FAT, meta server address:http://apollo.meta

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://apollo.meta/services/admin": apollo.meta; nested exception is java.net.UnknownHostException: apollo.meta
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:340)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.getAdminServerAddress(AdminServiceAddressLocator.java:141)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.refreshServerAddressCache(AdminServiceAddressLocator.java:121)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator.access$200(AdminServiceAddressLocator.java:43)
	at com.ctrip.framework.apollo.portal.component.AdminServiceAddressLocator$RefreshAdminServerAddressTask.run(AdminServiceAddressLocator.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: apollo.meta
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)

请问异常apollo.meta时什么原因？

**Comment by starsky20** [comment]
按照您提供的解决办法，分别验证了以下几种办法：
1.在apollo-env.properties设置中设置dev.meta=http://192.168.3.174:8080、apollo.meta=http://192.168.3.174:8080

2.在C:\opt\settings\server.properties 文件中添加env=DEV
![image](https://github.com/apolloconfig/apollo/assets/73730113/d8c7ed9a-2265-4620-b6d6-9e9c5ab91b66)

3.启动增加jvm参数 -Dapollo_profile=github -Denv=dev -Dapollo.meta=http://192.168.3.174:8080

以上三种方式都不可以，还是提示无法java.net.UnknownHostException: apollo.meta。调试代码后发现是env环境没有生效导致。
通过打成jar包后，修改application.yml的激活环境为github,dev,auth，然后在命令行直接执行 java -jar apollo-portal-2.3.0-SNAPSHOT.jar 启动无任务问题。

![image](https://github.com/apolloconfig/apollo/assets/73730113/e4278c99-e523-41d4-8d79-5ef6d3d09a61)

**Comment by nobodyiam** [comment]
可以在系统信息页面看到详情

![image](https://github.com/apolloconfig/apollo/assets/837658/ead56d5c-e415-4280-bc16-6805d6095436)
